### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by HexBewitched** [cornbotdiscord/site#6]
It might just be me but these links are pulling up non existent pages:
https://cornbot.dinois.fun/about
https://cornbot.dinois.fun/musicbot
https://cornbot.dinois.fun/cornbot
https://cornbot.dinois.fun/docs
https://cornbot.dinois.fun/jobs

**Comment by disnos9** [comment]
appraently cloudflare is being pissy, under investigation

**Comment by disnos9** [comment]
fixed, this was an issue with the custom domain not existing
